/* meld_section.h - Input section management and output section coalescing
 * Input sections from multiple .o files are merged into output sections (not segments, this is handled later) based on:
 *     1. Name matching
 *     2. Flag compatibility (SHF_ALLOC, SHF_WRITE, SHF_EXECINSTR)
 *     3. Alignment constraints
 *
 * Coalescing rules follow traditional linker semantics. 
 *
 * Copyright (c) 2025-2026 Felix Riley-Kay @ github.com/enfey
 */

#ifndef MELD_SECTION_H
#define MELD_SECTION_H

#include "meld.h"
#include <stdint.h>
#include <stdbool.h>
#include <elf.h>

/* Derived from input SHF_* flags' only a subset are handled as these are specifically for coalescing decisions */
#define OSEC_ALLOC       0x01
#define OSEC_WRITE       0x02
#define OSEC_EXEC        0x04
#define OSEC_NOBITS      0x08
#define OSEC_TLS         0x10
#define OSEC_LINK_ORDER  0x20
#define OSEC_RELRO       0x40
#define OSEC_SYNTHETIC   0x80  /* Generated by linker, not from input files */

/* Section IR; intentionally minimal, can determine section via *input and shndx, all data is queried via lens at runtime */
typedef struct meld_isec {
    meld_input_t       *input;
    uint32_t            shndx;
    uint32_t            output_off;
    struct meld_isec   *next;
} meld_isec_t;

/* Result of coalescing compatible input sections.
 *
 * Layout computed in 2 phases:
 *     1. Collection: input sections appended to `isecs` chain, forming non-realised meld_osec(s)
 *     2. Layout: compute `size`, assign `output_off` accordingly to each input section
 */
typedef struct meld_osec {
    const char         *name;       /* Section name */
    uint32_t            name_off;   /* Offset in .shstrtab, set at emit time */
    uint32_t            idx;        /* Index in output file (0=SHN_UNDEF) */

    uint8_t             flags;      /* OSEC_* flags */
    uint32_t            sh_type;
    uint32_t            sh_link;    /* Section header link (generally interpreted as a relation to another section) */
    uint32_t            sh_info;    /* Section header info */
    uint32_t            sh_entsize; /* Entry size for symbol/relocation tables */

    uint32_t            align;
    uint32_t            size;
    uint32_t            addr;       /* Virtual address (set during segment layout) */
    uint32_t            file_off;   /* File offset (set at emit time) */

    meld_isec_t        *isecs;
    meld_isec_t        *isecs_tail;
    uint32_t            isec_count;

    struct meld_osec   *next;
} meld_osec_t;

/* Maybe change this to a hash table? */
typedef struct {
    meld_osec_t        *sections;
    meld_osec_t        *tail;
    uint32_t            count;
} meld_section_mgr_t;

int  section_mgr_init(meld_section_mgr_t *mgr);
void section_mgr_destroy(meld_section_mgr_t *mgr);

/* Finds or creates an output section matching the input's name and flags
 * The input section is appended to the output section's chain
 */
meld_osec_t *section_add_input(meld_section_mgr_t *mgr, meld_input_t *input, uint32_t shndx);

meld_osec_t *section_find(meld_section_mgr_t *mgr, const char *name);

/* Create a synthetic output section e.g., .got, .plt, .dynamic, etc that the linker generates */
meld_osec_t *section_add_synthetic(meld_section_mgr_t *mgr, const char *name,
                                   uint8_t flags, uint32_t sh_type,
                                   uint32_t align, uint32_t size);

int section_layout(meld_section_mgr_t *mgr);

/* Iterates ctx->inputs[], for each input iterates sections, adds those
 * with SHF_ALLOC to the section manager. Non-ALLOC sections are skipped.
 */
int section_collect_all(meld_ctx_t *ctx, meld_section_mgr_t *mgr);

static inline uint8_t flags_from_elf(uint32_t sh_flags, uint32_t sh_type) {
    uint8_t f = 0;
    if (sh_flags & SHF_ALLOC)      f |= OSEC_ALLOC;
    if (sh_flags & SHF_WRITE)      f |= OSEC_WRITE;
    if (sh_flags & SHF_EXECINSTR)  f |= OSEC_EXEC;
    if (sh_flags & SHF_TLS)        f |= OSEC_TLS;
    if (sh_flags & SHF_LINK_ORDER) f |= OSEC_LINK_ORDER;
    if (sh_type == SHT_NOBITS)     f |= OSEC_NOBITS;
    return f;
}

/* Strips suffixes from section names: ".text.foo" → ".text", ".rodata.str1.4" → ".rodata"
 * Enables -ffunction-sections/-fdata-sections compiled objects to coalesce properly.
 */
const char *section_name_base(const char *name);

uint32_t section_index(meld_section_mgr_t *mgr, const char *name);

/* Assigns idx field to each section (1-based, 0=SHN_UNDEF)
 * Must be called before symtab population so st_shndx can be computed*/
void section_assign_indices(meld_section_mgr_t *mgr);

/* Fixes up sh_link, sh_info, and sh_entsize for dynamic linking sections */
void section_finalise_structure(meld_section_mgr_t *mgr,
                                uint32_t symtab_first_global,
                                uint32_t verdef_count,
                                uint32_t verneed_count);

#endif /* MELD_SECTION_H */
